### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by losominve** [FengWei2000/CBIR#2]
老师，在库中下载TensorFlow时跳出
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
请问应该怎么解决呢？

**Comment by FengWei2000** [comment]
这种属于TensorFlow这个框架的安装问题，比较麻烦，不太清楚你具体怎么安装的。不过建议使用conda开一个虚拟环境，python使用3.7版本，直接使用pip install tensorflow进行安装（运气好可能直接就成功了？）。如果有报错再去百度搜。

**Comment by losominve** [comment]
好的，我去试试，谢谢老师

**Comment by losominve** [comment]
我是在pycharm的teminal里直接pip install tensorflow -i https://pypi.douban.com/simple安装的，前面安装的一些都成功了，就到tensorflow出了问题

**Comment by FengWei2000** [comment]
> 

pycharm的我觉得不好用，经常下载慢且不成功（也因此很久没用过了，可能现在好用了？），不如用Anaconda Prompt。

**Comment by losominve** [comment]
好的，谢谢老师
