### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by losominve** [FengWei2000/CBIR#3]
在问一些我室友的问题：
1：ModuleNotFoundError: No module named '_pywrap_tensorflow'但pywrap_tensorflow好像不是安装包
2：Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter from there.不知道该如何解决。
拜托拜托

**Comment by FengWei2000** [comment]
都是tensorflow的安装问题。用conda开虚拟环境用pip下载试试吧，还有这种非项目的问题，还是尽量先找百度帮忙。

**Comment by losominve** [comment]
好的，我和室友都百度过了，没解决才来找您的

**Comment by FengWei2000** [comment]
> 

ok，能理解。tensorflow的安装确实不如pytorch，很有点坑。

**Comment by losominve** [comment]
老师，我室友tensorflow下载好了，但下一步就出现的上述问题

**Comment by FengWei2000** [comment]
> 老师，我室友tensorflow下载好了，但下一步就出现的上述问题

tensorflow版本是2.3.1吗？

**Comment by losominve** [comment]
0.12.0

**Comment by FengWei2000** [comment]
> 0.12.0

换成readme文件里写的版本

**Comment by losominve** [comment]
老师，我打开那个界面了，但我上传图片后点开始检索它就会未响应怎么办？

**Comment by losominve** [comment]
老师，我好像搞定了，谢谢老师
