### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by escape000** [FengWei2000/CBIR#4]
您好，我下载了百度网盘的压缩包，运行后报错AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'。可以加载出搜索页面，但是本地上传图片后，点击开始检索，就会报上面的错误，检索后的图片也显示不出来，请问该怎么解决呢？谢谢

**Comment by FengWei2000** [comment]
可能是keras包版本的问题，建议看一下之前的issues。
