### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wuhull** [FengWei2000/CBIR#5]
老师好，我想问一下运行之后显示：AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
怎么解决呀

**Comment by FengWei2000** [comment]
> 老师好，我想问一下运行之后显示：AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img' 怎么解决呀

正确的提问方式:
✔ 我这里遇到了一个问题:[问题描述]，我经过了以下尝试 [思路细节]，不能得到解决，报错如下:[报错截图] 请问该怎么解决?

我从你的提问只能得到报错的语句，只能猜测大概是keras库版本不对
